spring.application.name=pharmos-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pharmos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pharmos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pharmos}

spring.jpa.hibernate.ddl-auto=validate
